from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField, PasswordField, SelectField, IntegerField, BooleanField, DateField, TimeField, IntegerField, URLField, SubmitField
from wtforms.validators import InputRequired, Email, EqualTo, length, NumberRange, DataRequired, Length, Optional, URL
from flask_wtf.file import FileRequired, FileField, FileAllowed
from flask_sqlalchemy import SQLAlchemy
from .models import Event
from datetime import datetime

ALLOWED_FILE = {'PNG', 'JPG', 'JPEG', 'png', 'jpg', 'jpeg'}
  
# User login
class LoginForm(FlaskForm):
    user_name = StringField("User Name", validators=[InputRequired('Enter user name')])
    password = PasswordField("Password", validators=[InputRequired('Enter user password')])
    submit = SubmitField("Login")

# User register - UPDATED with all required fields
class RegisterForm(FlaskForm):
    first_name = StringField("First Name", validators=[InputRequired()])
    surname = StringField("Surname", validators=[InputRequired()])
    user_name = StringField("Username", validators=[InputRequired(), length(min=3, max=25)])
    email_id = StringField("Email Address", validators=[Email("Please enter a valid email")])
    contact_number = StringField("Contact Number", validators=[InputRequired()])
    street_address = StringField("Street Address", validators=[InputRequired()])
    
    # linking two fields - password should be equal to data entered in confirm
    password = PasswordField("Password", validators=[InputRequired(), 
                  length(min = 7, message="Passwords should be longer than 7 characters"),
                  EqualTo('confirm', message="Passwords should match")])
    confirm = PasswordField("Confirm Password")
    # submit button
    submit = SubmitField("Register")

class EventForm(FlaskForm):
    # All fields required except image_url
    title = StringField("Event Name", validators=[DataRequired(), Length(max=150)],
    render_kw={"id": "eventName", "class": "form-control"})

    artist_name = StringField("Artist/Band Name", validators=[DataRequired(), Length(max=150)],
    render_kw={"id": "artist", "class": "form-control"})

    genre = SelectField("Genre",
    choices=[("Rock","Rock"),("Jazz","Jazz"),("Indie","Indie"),("Electronic","Electronic"),("Hip Hop","Hip Hop")],
    validators=[DataRequired()],
    render_kw={"id": "genre", "class": "form-select"})

    capacity = IntegerField("Tickets Available", validators=[DataRequired(), NumberRange(min=1)],
    render_kw={"id": "tickets", "class": "form-control", "min": 1})

    price_per_ticket = IntegerField("Price per Ticket ($)", validators=[DataRequired(), NumberRange(min=1)],
    render_kw={"id": "price", "class": "form-control", "min": 1})

    venue_name = StringField("Venue", validators=[DataRequired(), Length(max=150)],
    render_kw={"id": "venue", "class": "form-control"})
    
    location = StringField("Location", validators=[DataRequired(), Length(max=150)],
    render_kw={"id": "location", "class": "form-control"})
    
    event_date = DateField("Date", validators=[DataRequired()],
    render_kw={"id": "date", "class": "form-control"})
    
    starts_at = TimeField("Start Time", validators=[DataRequired()],
    render_kw={"id": "time", "class": "form-control"})
    
    ends_at = TimeField("End Time", validators=[DataRequired()],
    render_kw={"id": "endTime", "class": "form-control"})
    
    image_url = URLField("Event Image URL", validators=[Optional(), URL()],
    render_kw={"id": "image", "class": "form-control"})
    
    description = TextAreaField("Description", validators=[DataRequired()],
    render_kw={"id": "desc", "class": "form-control", "rows": 5})
    
    submit = SubmitField("Create Event", render_kw={"class": "btn btn-primary btn-lg"})

class CommentForm(FlaskForm):
    # Text only input, user and event id generated by the logged in user id and the pages event id
    body = TextAreaField(
        "Your comment",
        validators=[DataRequired(), Length(min=1, max=1000)],
        render_kw={"rows": 3, "class": "form-control", "placeholder": "Share your thoughts..."}
    )
    submit = SubmitField("Post Comment", render_kw={"class": "btn btn-primary btn-sm"})


class CancelEventForm(FlaskForm):
    submit = SubmitField('Cancel Event')

# Ticket details
class TicketForm(FlaskForm): 
    event = SelectField("Select Event", validators=[InputRequired()], coerce=int)
    
    quantity = IntegerField("Quantity", validators=[InputRequired(),NumberRange(min=1, max=10, message="You can purchase 1-10 tickets")])
    
    # submit button
    submit = SubmitField("Buy Tickets")

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        self.update_event_choices()

    def update_event_choices(self):
        """Update event choices to only show available events"""
        try:
            # Get current open events with tickets available that are in the future
            from .models import Event
            from datetime import datetime
            
            available_events = Event.query.filter(
                Event.cancelled == False,
                Event.tickets_available > 0
            ).all()
            
            # Filter events that are in the future
            current_time = datetime.now()
            future_events = []
            
            for event in available_events:
                event_datetime = datetime.combine(event.event_date, event.starts_at)
                if event_datetime > current_time:
                    future_events.append(event)
            
            # Create choices for the dropdown
            choices = []
            for event in future_events:
                display_text = f"{event.title} - {event.venue_name} (${event.price_per_ticket} - {event.tickets_available} available)"
                choices.append((event.event_id, display_text))
            
            self.event.choices = choices
            
        except Exception as e:
            # If there's an error (like no database connection), set empty choices
            self.event.choices = []